name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master # Change this to the branch you want to trigger the deployment from

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Build and deploy
              run: |
                  cd ./packages/docs
                  yarn install
                  yarn run build
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git checkout --orphan gh-pages
                  git --work-tree ./.vitepress/dist add --all
                  git --work-tree dist commit -m "Deploy"
                  git push origin HEAD:gh-pages --force
